version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: medical-system-monolit
    volumes:
      - ./app:/var/www/html
      - ./app/storage:/var/www/html/storage
      - ./app/vendor:/var/www/html/vendor
    ports:
      - "80:80"
      - "5173:5173"
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=300
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=dev
      - DB_USERNAME=dev
      - DB_PASSWORD=dev
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: medical-system-db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    networks:
      - app-network
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
